- accounting/filters/OsgScheddCpuFilter.py
- accounting/formatters/OsgScheddCpuFormatter.py
Can only add two -- `ActivationDuration` and `ActivationSetupDuration` -- for now until HTCONDOR-908 and related issues (`condor_starter` version) are solved.
> Add activation time metrics

- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuHeldFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddCpuRemovedFilter.py
- accounting/filters/OsgScheddLongJobFilter.py
- cache_collector_hosts.py
There was a bug with how caching was done before with the same variables being used/overwritten. This PR fixes that and also only writes to the cache during the normal daily reports. Also, the mappings are updated every Monday in the normal daily report in case schedds change their collector hosts. Also, a script is added that can be run manually to update the cache periodically for all the current schedds reporting to the pool.
> Fix problems with caching collector hosts

- accounting/filters/ChtcScheddGpuFilter.py
The "site" list for GPU jobs get very large since IceCube tends to run in uniquely named glideins. This merges non-UW resources to "OSG via {ScheddName}"
> Compact GPU sites

- accounting/filters/BaseFilter.py
- accounting/filters/ChtcScheddCpuFilter.py
- accounting/filters/ChtcScheddCpuRemovedFilter.py
- accounting/filters/ChtcScheddGpuFilter.py
- accounting/filters/OsgScheddCpuHeldFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddCpuRemovedFilter.py
- accounting/filters/OsgScheddLongJobFilter.py
- send_email.py
Lately we've been running into an issue where the scroll timeout
is met and where queries in general are just taking too long. Also,
writing data to a JSON file before formatting has gotten very slow
as job counts have skyrocketed. This PR aims to improve the
situation by:
1. Setting a longer scroll, which starts at 30s and scales up by
the (square root) of the number of days in the query. This shouldn't
have a huge performance impact on the rest of the operations of ES
because the scan() helper function is supposed to clear scroll ids
as it finishes with them.
2. Query one index at a time, matching the index pattern given,
until no more data is found, then stop querying. Indices are queried
in reverse (chronological) order since most of our reports are done
by looking back at the last n …
> Improve report performance

- .gitignore
- accounting/filters/OsgScheddCpuRetryFilter.py
- accounting/filters/__init__.py
- accounting/formatters/OsgScheddCpuRetryFormatter.py
- accounting/formatters/__init__.py
- accounting/pull_hold_reasons.py
Adds a shadow retry report, and breaks down the number of extra shadows that were needed per project/user/AP by if they were related to transfer input errors. Still a bit of a work in progress, will update as more specs come in for this report.
> Add shadow retry report

- accounting/filters/OsgScheddCpuFilter.py
Changes reporting for OSDF data transfers to be "0" if there were no OSDF files or bytes transferred and the CondorVersion was >= 9.7.0 and "-" if there were no OSDF files or bytes transferred but the CondorVersion was < 9.7.0
> OSDF transfers reporting/non-reporting APs (INF-1416)

- accounting/formatters/OsgScheddCpuFormatter.py
This is a follow up to #49, where now `-`s in the OSDF columns are right-aligned so they look a bit less out of place.
> INF-1416 Align dashes in OSDF columns

- accounting/formatters/ChtcScheddCpuFormatter.py
- accounting/formatters/OsgScheddCpuFormatter.py
- accounting/formatters/OsgScheddGpuFormatter.py
- accounting/formatters/PathScheddCpuFormatter.py
Miron would like the definition of this column spelled out in the legend. For reference, this is what the manual says:
> ActivationSetupDuration
> Formally, the length of time in seconds from when the shadow sends a claim activation to when the shadow is notified that > the job was spawned.
>
> Informally, this is how long it took the starter to prepare to execute the job. That includes file transfer (including the time required to wait in the transfer queue), so the difference between this duration and the duration of input file transfer is (roughly) the execute-side overhead of preparing to start the job.
> INF-1520 Expand legend entries for activation setup time

- accounting/filters/BaseFilter.py
The previous fix for the position of the TOTAL row doesn't account for that row not existing, which occurs when there were not jobs for a given category/time-span, such as daily OSPool GPU usage.
> handle TOTAL row not existing exception

- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddGpuFilter.py
- accounting/formatters/OsgScheddCpuFormatter.py
- accounting/formatters/OsgScheddGpuFormatter.py
In OSG CPU/GPU reports:
Move job health indicators earlier in the report for INF-1858
Move Resource Usage columns to end of report for INF-1859
> (INF-1855) Report Column Shifts

- accounting/filters/ChtcScheddCpuFilter.py
- accounting/filters/ChtcScheddCpuMonthlyFilter.py
- accounting/filters/ChtcScheddCpuRemovedFilter.py
- accounting/formatters/ChtcScheddCpuFormatter.py
- accounting/formatters/ChtcScheddCpuRemovedFormatter.py
- accounting/formatters/ChtcScheddGpuFormatter.py
Before, the list of APs whose jobs we reported on was limited to the main, non-researcher dedicated APs. It has instead been requested that we report on all CHTC APs, regardless of purpose.
Also cleaned up a long-standing naming issue Schedd -> AP.
> INF-1917 Report on all CHTC APs in usage reports

- accounting/filters/BaseFilter.py
- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuHeldFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddCpuRemovedFilter.py
- accounting/filters/OsgScheddCpuRetryFilter.py
- accounting/filters/OsgScheddGpuFilter.py
- accounting/filters/OsgScheddLongJobFilter.py
- accounting/formatters/OsgScheddCpuFormatter.py
- accounting/formatters/OsgScheddCpuHeldFormatter.py
- accounting/formatters/OsgScheddCpuRemovedFormatter.py
- accounting/formatters/OsgScheddCpuRetryFormatter.py
- accounting/formatters/OsgScheddGpuFormatter.py
Now we're able to set `self.sort_col` in a filter class to set the column to sort the tables by. Still need some `merge_filtered_data()` override hackery to adjust the column names per table, but removes most of the need to override that method.
Starting off with just adjusting the OSPool reports. We should notify the RCFs before merging this so they're not caught off guard by the change in the sorting.
> INF-1856 Sort tables using arbitrary columns, make num jobs the sort column for most reports

- accounting/filters/OsgScheddCpuFilter.py
Some CHTC and OSG job Ads don't have a `CondorVersion` field, causing the version check for whether osdf transfer data is zero or non-reporting to fail by trying to envoke `.split()` on `None`. This fix will also go into the CHTC report when I finish homogenizing it with the OSG report.
> Fix for possible absent CondorVersion field in Osg report

- accounting/filters/ChtcScheddCpuFilter.py
- accounting/filters/ChtcScheddCpuMonthlyFilter.py
- accounting/filters/ChtcScheddCpuRemovedFilter.py
- accounting/filters/ChtcScheddGpuFilter.py
- accounting/formatters/ChtcScheddCpuFormatter.py
- accounting/formatters/ChtcScheddCpuRemovedFormatter.py
- accounting/formatters/ChtcScheddGpuFormatter.py
For the reports that are common to both OSPool and CHTC, the columns (and their ordering/sorting) should be the same for both reports (making the CHTC reports look like the OSPool reports).
Affected reports:
- CHTC Schedd CPU report and CPU Monthly report
- CHTC Schedd CPU Removed report
- CHTC Schedd GPU report
> (INF-1940) Homogenize the columns between OSPool and CHTC reports

- accounting/filters/ChtcScheddCpuFilter.py
- accounting/filters/ChtcScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/formatters/ChtcScheddCpuFormatter.py
- accounting/formatters/OsgScheddCpuFormatter.py
- accounting/functions.py
A basic job unit is defined as:
1 CPU
4 GB Memory
4 GB Disk
The number of job units that a job requests are the minimum number of units that are required to fulfill the request. For example, a job requesting 2 CPUs, 6 GB Memory, and 5 GB Disk would take up 2.0 units due to the CPU request. If that job requested 10 GB Memory instead, it would be 2.5 job units large.
The highlighted metric in this case is job unit hours, which is the number of job units times the total wallclock time, similar to CPU hours.
> INF-1954 Add job unit columns to CHTC and OSPool reports

- accounting/push_totals_to_es.py
- send_email.py
We don't want to open up the entire job classad database for public reads, but having the top-line totals from each day/week/month report is fine (and something we report on anyway). This code pushes data to an index that is read-only by the "default" user in the Tiger Elasticsearch instance.
The code added here is only enabled by having a JSON file containing the Elasticsearch connection info in a file named `tiger-es-summary-config.json`. I have provided this file for the `chtc_auto` user on `accounting3000`.
> INF-1594 Push daily totals to Tiger ES

- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddGpuFilter.py
- accounting/functions.py
Added a function that maps the "short IDs" (last part of the OSG and/or ROR IDs) to institution names, then use that function to determine the institution if a job ran on SDSC-PRP.
> INF-2488 Use actual cluster's institution for jobs that run on PRP

- accounting/filters/ChtcScheddCpuOspoolFilter.py
- accounting/filters/__init__.py
- accounting/formatters/ChtcScheddCpuOspoolFormatter.py
- accounting/formatters/__init__.py
Subset-ed to just those that ran on the OSPool.
For Jira Issue INF-2668.
> (INF-2668) Add report for CHTC jobs on the OSPool

- accounting/filters/BaseFilter.py
- accounting/filters/ChtcScheddCpuFilter.py
- accounting/filters/ChtcScheddCpuMonthlyFilter.py
- accounting/filters/ChtcScheddCpuOspoolFilter.py
- accounting/filters/ChtcScheddCpuOspoolMonthlyFilter.py
- accounting/filters/ChtcScheddCpuRemovedFilter.py
- accounting/filters/ChtcScheddDSIGpuFilter.py
- accounting/filters/ChtcScheddGpuFilter.py
- accounting/filters/IgwnScheddCpuFilter.py
- accounting/filters/OsgScheddCpuFilter.py
- accounting/filters/OsgScheddCpuHeldFilter.py
- accounting/filters/OsgScheddCpuMonthlyFilter.py
- accounting/filters/OsgScheddCpuRemovedFilter.py
- accounting/filters/OsgScheddCpuRetryFilter.py
- accounting/filters/OsgScheddGpuFilter.py
- accounting/filters/OsgScheddJobDistroFilter.py
- accounting/filters/OsgScheddLongJobFilter.py
- accounting/filters/PathScheddCpuFilter.py
- accounting/formatters/ChtcScheddCpuFormatter.py
- accounting/formatters/ChtcScheddCpuOspoolFormatter.py
- accounting/formatters/ChtcScheddCpuRemovedFormatter.py
- accounting/formatters/ChtcScheddGpuFormatter.py
- accounting/formatters/IgwnScheddCpuFormatter.py
- accounting/formatters/OsgScheddCpuFormatter.py
- accounting/formatters/OsgScheddCpuHeldFormatter.py
- accounting/formatters/OsgScheddCpuRemovedFormatter.py
- accounting/formatters/OsgScheddGpuFormatter.py
- accounting/formatters/PathScheddCpuFormatter.py
There are a lot of diffs, but they all do the same things:
1. Add a filter to the Elasticsearch query to ignore local and scheduler universe jobs
2. Remove checks for local and scheduler universe (i.e. no shadow) jobs
3. Update the rest of the code to account for the lack of those checks
4. Remove the local and scheduler universe columns and legend entries
> INF-2805 Remove local/scheduler universe usage

- accounting/filters/ChtcScheddCpuOspoolFilter.py
- accounting/filters/ChtcScheddCpuOspoolMonthlyFilter.py
Fixes for the csv names to include "OSPool" for INF-2931.
> (INF-2931) Fix csv names for "CHTC AP usage on OSPool" reports

- accounting/aggregations/osdf_report.py
- Re-order tables such that both download stats tables come first, then upload stats
- Allow for querying longer reporting periods (e.g. weekly, monthly)
- Add a legend for the columns
- Restrict the query to only return results for jobs that ran on the OSPool (i.e. removed CHTC local pool usage)
It looks like we still get a couple of `Undefined` resource names for jobs that were submitted from an OSPool AP but ran on a custom allocation, e.g. at Expanse.
> INF-3027 Requested OSDF report changes

- Dockerfile.ingest_monitor
- monitoring/ingest_monitor.py
This script:
1. Reads a config file containing a list of indexes (or aliases)
2. Takes a snapshot of the doc and size-on-disk counts for all indexes
3. Optionally uploads the snapshot back to Elasticsearch
4. Compares the snapshot with data on disk from the past half hour, hour, day, and week
5. Sends an error report (if any errors are encountered) to a specified "error" email address
6. If a regular "to" email address is specified, sends a report
> INF-3061 Add ingest monitoring script

- accounting/aggregations/osdf_report.py
Main change here is to split out 404 errors from non-404 errors. Just doing this would have made the report pretty lengthly (horizontally), so I also opted to remove some columns that haven't been used much. The legend has also been updated.
Behind the scenes, I also changed up how the columns are defined to make it easier to add or change the sorting of columns in the future.
> INF-3142 Split out 404 errors, re-work columns
